spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.serialization.AvroSerializer

grpc:
  server:
    port: 59091

collector:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO